from enum import StrEnum


class CaseStatus(StrEnum):
    NEW = "NEW"
    NEED_MORE_INFO = "NEED_MORE_INFO"
    DIAGNOSED = "DIAGNOSED"
    FOLLOWUP_PENDING = "FOLLOWUP_PENDING"
    FOLLOWUP_REVIEW = "FOLLOWUP_REVIEW"
    IMPROVING = "IMPROVING"
    WORSENING = "WORSENING"
    ESCALATED = "ESCALATED"
    CLOSED = "CLOSED"


class AgentAction(StrEnum):
    ASK_MORE_INFO = "ASK_MORE_INFO"
    DIAGNOSE_AND_PLAN = "DIAGNOSE_AND_PLAN"
    COMPARE_FOLLOWUP = "COMPARE_FOLLOWUP"
    ESCALATE = "ESCALATE"
    CLOSE_CASE = "CLOSE_CASE"


class EventType(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    USER_MESSAGE = "USER_MESSAGE"
    IMAGE_EVIDENCE_ADDED = "IMAGE_EVIDENCE_ADDED"
    VISION_ANALYZED = "VISION_ANALYZED"
    WEATHER_OBSERVED = "WEATHER_OBSERVED"
    SYMPTOMS_EXTRACTED = "SYMPTOMS_EXTRACTED"
    AGENT_DECISION = "AGENT_DECISION"
    AGENT_RESPONSE = "AGENT_RESPONSE"
    QUESTIONS_ASKED = "QUESTIONS_ASKED"
    DIAGNOSIS_GENERATED = "DIAGNOSIS_GENERATED"
    SAFETY_CHECKED = "SAFETY_CHECKED"
    PLAN_GENERATED = "PLAN_GENERATED"
    FOLLOWUP_CREATED = "FOLLOWUP_CREATED"
    REMINDER_CREATED = "REMINDER_CREATED"
    REMINDER_CANCELLED = "REMINDER_CANCELLED"
    FOLLOWUP_SUBMITTED = "FOLLOWUP_SUBMITTED"
    FOLLOWUP_COMPARED = "FOLLOWUP_COMPARED"
    STATE_CHANGED = "STATE_CHANGED"
    ESCALATED = "ESCALATED"
    CASE_CLOSED = "CASE_CLOSED"


class FollowupStatus(StrEnum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    DONE = "DONE"
    CANCELLED = "CANCELLED"


class FollowupTrend(StrEnum):
    IMPROVING = "IMPROVING"
    UNCHANGED = "UNCHANGED"
    WORSENING = "WORSENING"
    INSUFFICIENT_INFO = "INSUFFICIENT_INFO"
    NEEDS_HUMAN_CONFIRMATION = "NEEDS_HUMAN_CONFIRMATION"
